In [45]:
 #Q1 Write a Python program to create an array of 5 integers and display the array items. 
    
import numpy as np
np.random.seed(0)

intArray = np.random.randint(10, size = 5) #size - (total size of the array)
print("Type of intArray is:", type(intArray))
    
# Access individual element through indexes
for index in range(len(intArray)):
    print(intArray[index], end=' ')


Type of intArray is: <class 'numpy.ndarray'>
5 0 3 3 7 

In [46]:
#Q2 Write a Python program to reverse the order of the items in the array
print("Reverse of", intArray, "is:", np.flip(intArray))

Reverse of [5 0 3 3 7] is: [7 3 3 0 5]


In [32]:
#Q3 Create a 4X2 integer array and Prints its attributes 
intArray2D = np.random.randint(10, size = (4, 2))

#The shape of an array. shape - (size of each dimension); 
print("\nShape of intArray2D is:", intArray2D.shape)

#Array dimensions.
print("\nThe dimension of intArray2D is:", intArray2D.ndim)

#The Length of each element of the array in bytes.
print("\nDataType of array:", intArray2D.dtype) #The byte size depends on the data type of elements
print("The length/size of each element of the array in bytes:", intArray2D.itemsize)


Shape of intArray2D is: (4, 2)

The dimension of intArray2D is: 2

DataType of array: int32
The length/size of each element of the array in bytes: 4


In [10]:
# Q4 return array of items in the third column from all rows in the following numpy array
# ([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
intArrV2 = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
Column3 = intArrV2[:, 2]

print("Items in the 3rd Column:", Column3)


Items in the 3rd Column: [33 66 99]


In [44]:
#Q5 Create a result array by adding the following two NumPy arrays
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
resultArray = arrayOne + arrayTwo

print("The sum of the arrays:\n", resultArray)


The sum of the arrays:
 [[20 39 33]
 [25 25 28]]


In [25]:
#Q6 Sort the previous array
print("Sorted version of the Array:\n", np.sort(resultArray))


Sorted version of the Array:
 [[20 33 39]
 [25 25 28]]


In [6]:
#Functions vs Methods in Python
# Method - called using the dot operator and is associated with a python object
    # a set of instructions that are associated with an object
    # associated with an object; can't exists without it
# Function - invoked with the function name and is not associated a python object
    # set of instructions that perform a task
    # not associated with an object
    # example of built in functions we use print(), input(), reverse()